import * as THREE from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const $=s=>document.querySelector(s),canvas=$('#c'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.toneMapping=THREE.ACESFilmicToneMapping;const scene=new THREE.Scene();scene.background=new THREE.Color(0x11161b);scene.add(new THREE.HemisphereLight(0xdce8f2,0x25221f,1.8));const sun=new THREE.DirectionalLight(0xffedcf,3);sun.position.set(3,4,2);scene.add(sun);scene.add(new THREE.GridHelper(10,20,0x3b4650,0x20272d));const camera=new THREE.PerspectiveCamera(45,1,.01,100);camera.position.set(1.5,1.2,2.2);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;const loader=new GLTFLoader(),names=['MuzzleSocket','EjectionSocket','MagazineSocket','OpticSocket','MuzzleAttachmentSocket','UnderbarrelSocket','LeftHandSocket','RightHandSocket'],sockets={};let model=null,url=null;
const axes=$('#axes');for(const kind of['position','rotation']){const h=document.createElement('div');h.className='sel';h.innerHTML=`<b>${kind[0].toUpperCase()+kind.slice(1)}</b>`;for(const a of['x','y','z']){const row=document.createElement('div');row.className='axis';row.innerHTML=`<span>${a.toUpperCase()}</span><input data-kind="${kind}" data-axis="${a}" type="range" min="${kind==='position'?-2:-3.142}" max="${kind==='position'?2:3.142}" step=".001" value="0"><input data-kind="${kind}" data-axis="${a}" type="number" step=".001" value="0">`;h.appendChild(row)}axes.appendChild(h)}
function selected(){return sockets[$('#socket').value]}
function syncUI(){const s=selected();if(!s)return;for(const inp of document.querySelectorAll('[data-kind]')){const k=inp.dataset.kind,a=inp.dataset.axis,v=k==='rotation'?s.rotation[a]:s.position[a];inp.value=Number(v).toFixed(3)}}
function marker(name,obj){const g=new THREE.Group();g.name=name;const m=new THREE.Mesh(new THREE.SphereGeometry(.018,10,8),new THREE.MeshBasicMaterial({color:0xffc85e,depthTest:false}));const ax=new THREE.AxesHelper(.12);g.add(m,ax);if(obj){obj.getWorldPosition(g.position);obj.getWorldQuaternion(g.quaternion)}scene.add(g);return g}
function rebuildSockets(){for(const s of Object.values(sockets))scene.remove(s);for(const n of names){const o=model?.getObjectByName(n);sockets[n]=marker(n,o)}syncUI();renderOut()}
function renderOut(){const data={};for(const[n,s]of Object.entries(sockets))data[n]={position:s.position.toArray().map(v=>+v.toFixed(4)),rotation:[s.rotation.x,s.rotation.y,s.rotation.z].map(v=>+v.toFixed(4))};$('#out').textContent=JSON.stringify({sockets:data},null,2)}
document.addEventListener('input',e=>{const inp=e.target;if(!inp.dataset.kind)return;const pair=[...document.querySelectorAll(`[data-kind="${inp.dataset.kind}"][data-axis="${inp.dataset.axis}"]`)];for(const p of pair)if(p!==inp)p.value=inp.value;const s=selected(),v=+inp.value;if(inp.dataset.kind==='position')s.position[inp.dataset.axis]=v;else s.rotation[inp.dataset.axis]=v;renderOut()});$('#socket').onchange=syncUI;$('#copy').onclick=()=>navigator.clipboard?.writeText($('#out').textContent);
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(model)scene.remove(model);if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);const gltf=await loader.loadAsync(url);model=gltf.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});const b=new THREE.Box3().setFromObject(model),c=b.getCenter(new THREE.Vector3()),sz=b.getSize(new THREE.Vector3()),r=Math.max(sz.x,sz.y,sz.z);controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(r*1.1,r*.7,r*1.6));rebuildSockets()};
function loop(){requestAnimationFrame(loop);const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w||canvas.height!==h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}controls.update();renderer.render(scene,camera)}loop();
