import * as THREE from 'three/webgpu';

const PART_HINTS={slide:/slide/i,bolt:/bolt|charging.?handle/i,magazine:/mag|clip/i,trigger:/trigger/i};
export class FPSViewModel {
  constructor(camera,assets){this.camera=camera;this.assets=assets;this.root=new THREE.Group();this.root.name='FPSViewModelRoot';camera.add(this.root);this.weaponRoot=new THREE.Group();this.armRoot=new THREE.Group();this.root.add(this.armRoot,this.weaponRoot);this.weapon=null;this.arms=null;this.parts={};this.rest=new Map();this.ads=false;this.reloading=false;this.reloadT=0;this.reloadEvents=new Set();this.onReloadEvent=null;this.recoilKick=0;this.recoilYaw=0;this.inertiaX=0;this.inertiaY=0;this.lastYaw=0;this.lastPitch=0;this.baseHip=new THREE.Vector3(.28,-.23,-.48);this.baseAds=new THREE.Vector3(0,-.13,-.36)}
  clear(group){while(group.children.length)group.remove(group.children[0])}
  prepMeshes(root){root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=false;o.frustumCulled=false;if(o.material){o.material.depthTest=true;o.material.depthWrite=true}}})}
  alignLongAxis(root,targetLength=.92){root.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3());if(size.x>=size.y&&size.x>=size.z)root.rotation.y=Math.PI/2;else if(size.y>=size.x&&size.y>=size.z)root.rotation.x=-Math.PI/2;root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);size=box.getSize(new THREE.Vector3());const longest=Math.max(size.x,size.y,size.z,.0001);root.scale.multiplyScalar(targetLength/longest);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);const center=box.getCenter(new THREE.Vector3());root.position.sub(center)}
  async loadArms(url){try{const gltf=await this.assets.loadGLB(url,{clone:true});this.clear(this.armRoot);this.arms=gltf.scene;this.prepMeshes(this.arms);this.alignLongAxis(this.arms,1.15);this.arms.position.set(-.02,-.38,-.30);this.arms.rotation.z=.02;this.armRoot.add(this.arms);return true}catch(e){console.warn('FPS arms load failed',e);return false}}
  async loadWeapon(def){try{const gltf=await this.assets.loadGLB(def.model,{clone:true});this.clear(this.weaponRoot);this.parts={};this.rest.clear();this.weapon=gltf.scene;this.prepMeshes(this.weapon);this.alignLongAxis(this.weapon,def.viewLength||.9);this.weapon.position.set(0,0,0);this.weaponRoot.add(this.weapon);this.weapon.traverse(o=>{for(const[k,re]of Object.entries(PART_HINTS))if(!this.parts[k]&&re.test(o.name||'')){this.parts[k]=o;this.rest.set(o,{position:o.position.clone(),rotation:o.rotation.clone()})}});this.weaponRoot.position.copy(this.baseHip);this.weaponRoot.rotation.set(.015,-.03,-.015);return true}catch(e){console.warn('Weapon model load failed',def?.model,e);return false}}
  setADS(v){this.ads=!!v}
  recoil(amount=1){this.recoilKick=Math.min(.12,this.recoilKick+.038*amount);this.recoilYaw+=(Math.random()-.5)*.018*amount;const p=this.parts.slide||this.parts.bolt;if(p){const r=this.rest.get(p);if(r)p.position.z=r.position.z+.035}}
  reload(onEvent){if(this.reloading)return false;this.reloading=true;this.reloadT=0;this.reloadEvents.clear();this.onReloadEvent=onEvent||null;return true}
  emitReload(name){if(this.reloadEvents.has(name))return;this.reloadEvents.add(name);this.onReloadEvent?.(name)}
  update(dt,{time=0,speed=0,sprint=false,crouch=false,slide=0,yaw=0,pitch=0}={}){const yawDelta=THREE.MathUtils.clamp(yaw-this.lastYaw,-.08,.08),pitchDelta=THREE.MathUtils.clamp(pitch-this.lastPitch,-.08,.08);this.lastYaw=yaw;this.lastPitch=pitch;this.inertiaX=THREE.MathUtils.damp(this.inertiaX,-yawDelta*1.15,13,dt);this.inertiaY=THREE.MathUtils.damp(this.inertiaY,pitchDelta*.85,13,dt);const moving=Math.min(1,speed/6),freq=sprint?12.5:8.5,bobY=Math.sin(time*freq)*.014*moving,bobX=Math.cos(time*freq*.5)*.011*moving,target=this.ads?this.baseAds:this.baseHip;this.weaponRoot.position.x=THREE.MathUtils.damp(this.weaponRoot.position.x,target.x+bobX+this.inertiaX,16,dt);this.weaponRoot.position.y=THREE.MathUtils.damp(this.weaponRoot.position.y,target.y+bobY+this.inertiaY+(crouch?-.03:0),16,dt);this.weaponRoot.position.z=THREE.MathUtils.damp(this.weaponRoot.position.z,target.z+this.recoilKick+(sprint?.08:0),18,dt);const slideTilt=slide>0?-.14*(slide/.58):0;this.weaponRoot.rotation.z=THREE.MathUtils.damp(this.weaponRoot.rotation.z,slideTilt+(sprint?.08:0)+this.recoilYaw,13,dt);this.weaponRoot.rotation.x=THREE.MathUtils.damp(this.weaponRoot.rotation.x,this.reloading?-.15:.015-this.recoilKick*.7,17,dt);this.recoilKick=THREE.MathUtils.damp(this.recoilKick,0,22,dt);this.recoilYaw=THREE.MathUtils.damp(this.recoilYaw,0,18,dt);const movingPart=this.parts.slide||this.parts.bolt;if(movingPart&&!this.reloading){const r=this.rest.get(movingPart);if(r)movingPart.position.lerp(r.position,1-Math.exp(-32*dt))}if(this.reloading){this.reloadT+=dt;const t=this.reloadT/1.55;this.weaponRoot.rotation.z=-Math.sin(Math.min(1,t)*Math.PI)*.42;const mag=this.parts.magazine,r=mag&&this.rest.get(mag);if(mag&&r){const drop=t<.46?Math.max(0,(t-.12)/.34):Math.max(0,1-(t-.46)/.34);mag.position.copy(r.position);mag.position.y-=drop*.25}if(t>.12)this.emitReload('magOut');if(t>.50)this.emitReload('magIn');if(t>.76)this.emitReload('bolt');if(t>=1){this.reloading=false;this.weaponRoot.rotation.z=0;if(mag&&r)mag.position.copy(r.position);this.emitReload('complete')}}this.armRoot.position.x=THREE.MathUtils.damp(this.armRoot.position.x,bobX*.7,14,dt);this.armRoot.position.y=THREE.MathUtils.damp(this.armRoot.position.y,bobY*.7,14,dt)}
}
