export const WEAPON_DEFINITIONS={
  m4:{id:'m4',class:'assault-rifle',displayName:'M4 Platform',audio:{layer:'weapons_player',bank:'lmg_combat'},magazine:30,reserve:120,fireRate:700,damage:34,muzzleVelocity:880,recoil:{pitch:.012,yaw:.004,recovery:18},attachments:['optic','muzzle','underbarrel','magazine','side']},
  ak:{id:'ak',class:'assault-rifle',displayName:'AK Platform',audio:{layer:'weapons_player',bank:'lmg_mg_player'},magazine:30,reserve:120,fireRate:600,damage:38,muzzleVelocity:715,recoil:{pitch:.016,yaw:.007,recovery:15},attachments:['optic','muzzle','underbarrel','magazine','side']},
  combatPistol:{id:'combat-pistol',class:'pistol',displayName:'Combat Pistol',audio:{layer:'weapons_player',bank:'ptl_combat'},magazine:15,reserve:60,fireRate:420,damage:28,muzzleVelocity:360,recoil:{pitch:.022,yaw:.006,recovery:14},attachments:['optic','muzzle','magazine']},
  pistol:{id:'pistol',class:'pistol',displayName:'Service Pistol',audio:{layer:'weapons_player',bank:'ptl_pistol'},magazine:17,reserve:68,fireRate:420,damage:26,muzzleVelocity:350,recoil:{pitch:.02,yaw:.005,recovery:15},attachments:['optic','muzzle','magazine']},
  smg:{id:'smg',class:'smg',displayName:'SMG',audio:{layer:'weapons_player',bank:'smg_smg'},magazine:30,reserve:150,fireRate:800,damage:24,muzzleVelocity:400,recoil:{pitch:.009,yaw:.006,recovery:20},attachments:['optic','muzzle','underbarrel','magazine']},
  microSmg:{id:'micro-smg',class:'smg',displayName:'Micro SMG',audio:{layer:'weapons_player',bank:'smg_micro'},magazine:30,reserve:150,fireRate:900,damage:21,muzzleVelocity:360,recoil:{pitch:.01,yaw:.008,recovery:20},attachments:['optic','muzzle','magazine']},
  pumpShotgun:{id:'pump-shotgun',class:'shotgun',displayName:'Pump Shotgun',audio:{layer:'weapons_player',bank:'sht_pump'},magazine:8,reserve:40,fireRate:75,damage:18,pellets:8,muzzleVelocity:400,recoil:{pitch:.06,yaw:.01,recovery:8},attachments:['optic','muzzle']},
  bullpupShotgun:{id:'bullpup-shotgun',class:'shotgun',displayName:'Bullpup Shotgun',audio:{layer:'weapons_player',bank:'sht_bullpup'},magazine:10,reserve:40,fireRate:220,damage:15,pellets:8,muzzleVelocity:410,recoil:{pitch:.045,yaw:.012,recovery:10},attachments:['optic','muzzle']},
  sniper:{id:'sniper',class:'sniper',displayName:'Marksman Rifle',audio:{layer:'weapons_player',bank:'snp_rifle'},magazine:10,reserve:40,fireRate:55,damage:90,muzzleVelocity:900,recoil:{pitch:.08,yaw:.012,recovery:7},attachments:['optic','muzzle']},
  heavySniper:{id:'heavy-sniper',class:'sniper',displayName:'Heavy Sniper',audio:{layer:'weapons_player',bank:'snp_heavy'},magazine:5,reserve:25,fireRate:40,damage:130,muzzleVelocity:950,recoil:{pitch:.11,yaw:.014,recovery:6},attachments:['optic','muzzle']},
  revolver:{id:'revolver',class:'revolver',displayName:'Revolver',audio:{layer:'dlc_weapons',bank:'ptl_revolver'},magazine:6,reserve:36,fireRate:150,damage:55,muzzleVelocity:430,recoil:{pitch:.045,yaw:.012,recovery:10},attachments:[]},
  doubleBarrel:{id:'double-barrel',class:'shotgun',displayName:'Double Barrel',audio:{layer:'dlc_weapons',bank:'db_shotgun'},magazine:2,reserve:30,fireRate:120,damage:22,pellets:9,muzzleVelocity:420,recoil:{pitch:.085,yaw:.015,recovery:7},attachments:[]}
};

export function getWeaponDefinition(id){return WEAPON_DEFINITIONS[id]||WEAPON_DEFINITIONS.m4}
