import * as THREE from 'three/webgpu';
import { clone as skeletonClone } from 'three/addons/utils/SkeletonUtils.js';

function fitObject(root,{size=4,height=null}={}){root.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(root),s=box.getSize(new THREE.Vector3());const denom=height?s.y:Math.max(s.x,s.y,s.z),scale=(height||size)/Math.max(.0001,denom);root.scale.multiplyScalar(scale);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);const c=box.getCenter(new THREE.Vector3());root.position.sub(c);root.updateMatrixWorld(true);return root}

export async function createStage3Arena(scene,assets,{mobile=false}={}){
  const root=new THREE.Group();root.name='Stage3Arena';scene.add(root);const colliders=[],targets=[];
  const wet=new THREE.MeshPhysicalMaterial({color:0x22292d,roughness:.27,metalness:.04,clearcoat:.55,clearcoatRoughness:.18}),concrete=new THREE.MeshStandardMaterial({color:0x5f676a,roughness:.9,metalness:.02}),dark=new THREE.MeshStandardMaterial({color:0x252b2f,roughness:.68,metalness:.18});
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(110,110),wet);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;root.add(floor);
  function block(x,y,z,sx,sy,sz,mat=concrete,visible=true){const mesh=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;mesh.visible=visible;root.add(mesh);colliders.push(new THREE.Box3(new THREE.Vector3(x-sx/2,y-sy/2,z-sz/2),new THREE.Vector3(x+sx/2,y+sy/2,z+sz/2)));return mesh}
  block(0,2,-25,52,4,2);block(0,2,25,52,4,2);block(-26,2,0,2,4,52);block(26,2,0,2,4,52);block(-10,1.5,-10,10,3,1,dark);block(10,1.5,-10,10,3,1,dark);block(-12,1.5,6,1,3,14);block(12,1.5,6,1,3,14);block(0,1.5,14,15,3,1);block(0,1.5,1,8,3,1);block(-19,1,-14,5,2,6,dark,false);block(18,1,14,5,2,6,dark,false);block(-18,1,18,4,2,4,dark,false);block(18,1,-18,4,2,4,dark,false);
  const cyan=new THREE.MeshStandardMaterial({color:0x081215,emissive:0x28d7ff,emissiveIntensity:4.2,roughness:.38}),amber=new THREE.MeshStandardMaterial({color:0x170d05,emissive:0xff7b22,emissiveIntensity:3.3,roughness:.42});
  for(const[x,z,c]of[[-25,-8,cyan],[25,8,amber],[-9,-24,amber],[11,24,cyan]]){const strip=new THREE.Mesh(new THREE.BoxGeometry(.08,1.5,4.5),c);strip.position.set(x,2.4,z);root.add(strip);const light=new THREE.PointLight(c===cyan?0x37c9ff:0xff8c3b,mobile?10:22,11,2);light.position.set(x+(x<0?.8:-.8),2.7,z);root.add(light)}
  async function place(url,pos,{size=4,height=null,rot=0}={}){try{const g=await assets.loadGLB(url,{clone:true}),holder=new THREE.Group(),model=g.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=true}});fitObject(model,{size,height});holder.add(model);holder.position.copy(pos);holder.rotation.y=rot;root.add(holder);return holder}catch(e){console.warn('Arena asset failed',url,e);return null}}
  const jobs=[place('./game-assets/models/environment/cover/concrete_road_barrier.glb',new THREE.Vector3(-19,0,-14),{size:4.8,rot:.15}),place('./game-assets/models/environment/cover/old_military_crate.glb',new THREE.Vector3(18,0,14),{size:3.8,rot:-.4}),place('./game-assets/models/environment/terrain/boulder_01.glb',new THREE.Vector3(-18,0,18),{size:4.2,rot:.6}),place('./game-assets/models/environment/buildings/kenney-industrial/building-f.glb',new THREE.Vector3(-31,3,-8),{height:10,rot:Math.PI/2}),place('./game-assets/models/environment/buildings/kenney-industrial/building-j.glb',new THREE.Vector3(31,3,10),{height:11,rot:-Math.PI/2}),place('./game-assets/models/environment/buildings/kenney-industrial/building-r.glb',new THREE.Vector3(0,3,-31),{height:9,rot:0})];
  let operatorSource=null,operatorAnimations=[];try{const g=await assets.loadGLB('./game-assets/models/characters/operators/bamen_military_soldier_animated.glb');operatorSource=g.scene;operatorAnimations=g.animations||[]}catch(e){console.warn('Operator asset unavailable',e)}
  function fallbackTarget(){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.95,4,8),dark),head=new THREE.Mesh(new THREE.SphereGeometry(.27,14,10),new THREE.MeshStandardMaterial({color:0x78685d,roughness:.8}));body.position.y=1.15;head.position.y=2.02;g.add(body,head);head.userData.hitZone='head';return g}
  for(const[x,z,r]of[[0,-17,0],[-17,7,1.2],[17,-5,-1.1],[6,19,3.1]]){const visual=operatorSource?skeletonClone(operatorSource):fallbackTarget();if(operatorSource)fitObject(visual,{height:1.82});const t=new THREE.Group();t.position.set(x,0,z);t.rotation.y=r;t.add(visual);t.userData={health:100,alive:true,respawn:0,mixer:null};root.add(t);visual.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.userData.target=t;if(/head|helmet|skull/i.test(o.name||''))o.userData.hitZone='head'}});if(operatorAnimations.length){const mixer=new THREE.AnimationMixer(visual),clip=operatorAnimations.find(c=>/idle/i.test(c.name))||operatorAnimations[0];if(clip)mixer.clipAction(clip).play();t.userData.mixer=mixer}targets.push(t)}
  await Promise.allSettled(jobs);return{root,colliders,targets,update(dt){for(const t of targets)t.userData.mixer?.update(dt)}};
}
