export class AudioManager {
  constructor(){this.ctx=null;this.master=null;this.weaponBus=null;this.compressor=null;this.layers={resident:new Map(),weapons_player:new Map(),dlc_weapons:new Map()};this.manifests=[];this.permanentLoaded=false;this.loading=new Map()}
  async unlock(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;this.ctx=new C({latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.gain.value=.82;this.weaponBus=this.ctx.createGain();this.weaponBus.gain.value=.92;this.compressor=this.ctx.createDynamicsCompressor();this.compressor.threshold.value=-12;this.compressor.knee.value=10;this.compressor.ratio.value=4;this.compressor.attack.value=.003;this.compressor.release.value=.16;this.weaponBus.connect(this.compressor);this.compressor.connect(this.master);this.master.connect(this.ctx.destination)}if(this.ctx.state==='suspended')await this.ctx.resume()}
  clear(){for(const layer of Object.values(this.layers))layer.clear();this.manifests.length=0;this.permanentLoaded=false;this.loading.clear()}
  detectLayer(path=''){const p=String(path).toLowerCase();if(p.includes('dlc_weapons'))return'dlc_weapons';if(p.includes('resident'))return'resident';return'weapons_player'}
  normalizeBank(source='',fallback=''){const clean=String(source||fallback).replace(/\\/g,'/'),file=clean.split('/').pop()||clean;return file.replace(/\.awc$/i,'').replace(/^weapons_player_/i,'').replace(/^dlc_weapons_/i,'').replace(/^resident_/i,'')}
  ensureBank(layer,bank){const map=this.layers[layer];if(!map.has(bank))map.set(bank,[]);return map.get(bank)}
  async decodeArrayBuffer(arr){await this.unlock();return this.ctx.decodeAudioData(arr.slice(0))}
  async fetchDecode(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${url}`);return this.decodeArrayBuffer(await r.arrayBuffer())}
  async importZip(file,{replace=false}={}){if(!window.JSZip)throw new Error('ZIP support failed to load.');await this.unlock();if(replace)this.clear();const zip=await JSZip.loadAsync(file),entries=Object.values(zip.files).filter(x=>!x.dir),manifestEntry=entries.find(x=>/audio-manifest\.json$/i.test(x.name));let manifest=null;if(manifestEntry){try{manifest=JSON.parse(await manifestEntry.async('text'));this.manifests.push(manifest)}catch(err){console.warn('Audio manifest parse failed',err)}}const metadata=new Map();if(manifest?.banks)for(const bankMeta of manifest.banks){const layer=this.detectLayer(bankMeta.source||bankMeta.id),bank=this.normalizeBank(bankMeta.source,bankMeta.id);for(const stream of bankMeta.streams||[]){const basename=(stream.file||'').split('/').pop();if(basename)metadata.set(basename.toLowerCase(),{layer,bank,stream})}}if(manifest?.files)for(const stream of manifest.files){const basename=(stream.path||'').split('/').pop();if(basename)metadata.set(basename.toLowerCase(),{layer:stream.layer||this.detectLayer(stream.path),bank:stream.bank||this.normalizeBank(stream.source,stream.path),stream})}let loaded=0,failed=0;const layerCounts={resident:0,weapons_player:0,dlc_weapons:0};for(const entry of entries){if(!/\.wav$/i.test(entry.name))continue;try{const basename=entry.name.split('/').pop().toLowerCase(),meta=metadata.get(basename),layer=meta?.layer||this.detectLayer(entry.name),bank=meta?.bank||this.normalizeBank('',entry.name.split('/').slice(-2,-1)[0]),buffer=await this.decodeArrayBuffer(await entry.async('arraybuffer'));this.ensureBank(layer,bank).push({buffer,url:null,id:meta?.stream?.streamId||meta?.stream?.id||basename.replace(/\.wav$/i,''),index:meta?.stream?.streamIndex??meta?.stream?.index??loaded,source:entry.name,duration:buffer.duration,kind:meta?.stream?.kind||''});loaded++;layerCounts[layer]++}catch(err){failed++;console.warn('Audio decode failed:',entry.name,err)}}return{loaded,failed,layers:layerCounts,banks:Object.fromEntries(Object.entries(this.layers).map(([k,v])=>[k,v.size]))}}
  async loadPermanent(){if(this.permanentLoaded)return;try{const r=await fetch('./game-assets/audio/audio-manifest.json',{cache:'no-cache'});if(!r.ok)throw new Error(`${r.status} audio manifest`);const manifest=await r.json();this.manifests.push(manifest);for(const stream of manifest.files||[]){const layer=stream.layer||this.detectLayer(stream.path||stream.source),bank=stream.bank||this.normalizeBank(stream.source,stream.path);if(!this.layers[layer]||!bank)continue;const dest=this.ensureBank(layer,bank),id=stream.streamId||stream.id||String(stream.streamIndex??dest.length);if(dest.some(x=>x.id===id))continue;const relative=String(stream.path||'').replace(/^public\/game-assets\//,'./game-assets/');dest.push({buffer:null,url:new URL(relative,document.baseURI).href,id,index:stream.streamIndex??stream.index??dest.length,source:stream.path,duration:stream.duration||0,kind:stream.kind||''})}for(const bankMeta of manifest.banks||[]){const layer=this.detectLayer(bankMeta.source||bankMeta.id),bank=this.normalizeBank(bankMeta.source,bankMeta.id),dest=this.ensureBank(layer,bank);for(const stream of bankMeta.streams||[]){const id=stream.id||String(stream.index??dest.length);if(dest.some(x=>x.id===id))continue;const relative=String(stream.file||'').replace(/^public\/game-assets\//,'./game-assets/');dest.push({buffer:null,url:new URL(relative,document.baseURI).href,id,index:stream.index??dest.length,source:stream.file,duration:stream.duration||0,kind:stream.kind||''})}}}catch(err){console.warn('Permanent Project Strike audio unavailable',err)}this.permanentLoaded=true}
  async preloadBank(layer,bank,{limit=18}={}){await this.loadPermanent();const streams=this.getBank(layer,bank);if(!streams?.length)return 0;const ordered=[...streams].sort((a,b)=>{const score=s=>(/audio clip/i.test(s.kind)?3:0)+(s.duration>=.08?2:0)+(/short|component/i.test(s.kind)?1:0);return score(b)-score(a)}).slice(0,limit);let n=0;for(const s of ordered){if(s.buffer){n++;continue}if(!s.url)continue;const key=s.url;try{if(!this.loading.has(key))this.loading.set(key,this.fetchDecode(key));s.buffer=await this.loading.get(key);n++}catch(err){console.warn('Audio fetch failed',s.url,err)}finally{this.loading.delete(key)}}return n}
  async preloadWeapon(bank){await this.loadPermanent();for(const layer of ['weapons_player','dlc_weapons'])if(this.layers[layer].has(bank))return this.preloadBank(layer,bank);return 0}
  getBank(layer,bank){return this.layers[layer]?.get(bank)||null}
  findBank(bank){for(const layer of ['weapons_player','dlc_weapons','resident']){const exact=this.layers[layer].get(bank);if(exact?.length)return{layer,bank,streams:exact};for(const[name,streams]of this.layers[layer])if(name.includes(bank)||bank.includes(name))return{layer,bank:name,streams}}return null}
  chooseStream(streams,{mechanical=false}={}){const ready=streams?.filter(s=>s.buffer)||[];if(!ready.length)return null;let preferred=mechanical?ready.filter(s=>/short|component/i.test(s.kind)||s.duration&&s.duration<.12):ready.filter(s=>/audio clip/i.test(s.kind)||s.duration>=.08);if(!preferred.length)preferred=ready;return preferred[Math.floor(Math.random()*preferred.length)]}
  playBuffer(buffer,{gain=1,rate=1,position=null,lowpass=null,bus='weapon'}={}){if(!buffer||!this.ctx)return null;const src=this.ctx.createBufferSource();src.buffer=buffer;src.playbackRate.value=rate;const g=this.ctx.createGain();g.gain.value=gain;let tail=g;if(lowpass){const f=this.ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=lowpass;g.connect(f);tail=f}const output=bus==='master'?this.master:this.weaponBus;if(position&&this.ctx.createPanner){const p=this.ctx.createPanner();p.panningModel='HRTF';p.distanceModel='inverse';p.refDistance=2;p.maxDistance=180;p.rolloffFactor=1.1;p.positionX.value=position.x;p.positionY.value=position.y;p.positionZ.value=position.z;src.connect(g);tail.connect(p);p.connect(output)}else{src.connect(g);tail.connect(output)}src.start();return src}
  playBank(layer,bank,opts={}){const stream=this.chooseStream(this.getBank(layer,bank));if(stream)return this.playBuffer(stream.buffer,opts);this.preloadBank(layer,bank).catch(()=>{});return null}
  play(layer,contains,opts={}){const map=this.layers[layer];if(!map)return null;for(const[name]of map)if(name.includes(contains)||contains.includes(name))return this.playBank(layer,name,opts);return null}
  playWeaponShot(bank='lmg_combat',opts={}){const hit=this.findBank(bank);if(!hit){this.preloadWeapon(bank).catch(()=>{});return null}const stream=this.chooseStream(hit.streams);if(!stream){this.preloadBank(hit.layer,hit.bank).catch(()=>{});return null}return this.playBuffer(stream.buffer,{gain:.82,rate:.988+Math.random()*.024,...opts})}
  playWeaponMechanical(bank,opts={}){const hit=this.findBank(bank);if(!hit){this.preloadWeapon(bank).catch(()=>{});return null}const stream=this.chooseStream(hit.streams,{mechanical:true});if(!stream){this.preloadBank(hit.layer,hit.bank).catch(()=>{});return null}return this.playBuffer(stream.buffer,{gain:.2,rate:.99+Math.random()*.02,...opts})}
  playResident(bank,opts={}){return this.playBank('resident',bank,{bus:'master',...opts})}
}
