export const STAGES=[
  {id:1,name:'Playable FPS Foundation',status:'complete',items:['Three.js renderer','desktop + mobile input','sprint/crouch/slide/jump','ADS/fire/reload','targets/damage/respawn','shell casings','repository-backed audio']},
  {id:2,name:'Production Systems',status:'complete',items:['GLB/KTX2/Draco/Meshopt asset pipeline','Rapier WASM foundation','PBR materials + LOD','weapon/character loaders','multiplayer room/snapshot foundation','dynamic mobile quality','permanent three-layer audio']},
  {id:3,name:'Hero Weapons + Character',status:'complete',items:['real M4/AK/SMG/pistol/sniper assets','separate rigged first-person arm layer','animated military operators','weapon socket discovery + synthetic fallback sockets','red-dot/holo attachment support','embedded clip playback + procedural viewmodel motion']},
  {id:4,name:'Combat + Effects Polish',status:'active',items:['fault-tolerant renderer / black-screen recovery','deterministic recoil patterns','lingering muzzle smoke','surface sparks + bullet decals','frag + flashbang gameplay','flash visual/ringing response','sniper scope overlay','footstep/environment audio','death animation + ragdoll-lite fallback','wet ground + puddles + rain','all committed weapon catalog wired']},
  {id:5,name:'Maps + Visual Fidelity',status:'active',items:['real enterable industrial building district','selective wet-surface PBR response','cyan/magenta/amber practical lighting','stable desktop WebGL bloom path','mobile direct-PBR stability path','additional maps and material tagging next']},
  {id:6,name:'Online Multiplayer',status:'queued',items:['existing room/snapshot client foundation retained','authoritative simulation','client prediction','server reconciliation','lag compensation','TDM/FFA','anti-cheat validation']},
  {id:7,name:'Content + Release',status:'queued',items:['full authored animation coverage per weapon','true physics ragdolls','gunsmith/customization','map editor','asset pack streaming','PWA install/cache','iPhone performance certification']}
];
