export const STAGES=[
  {id:1,name:'Playable FPS Foundation',status:'complete',items:['Three.js renderer','Killhouse blockout','desktop + mobile input','sprint/crouch/slide/jump','ADS/fire/reload','targets/damage/respawn','shell casings','three-layer audio']},
  {id:2,name:'Production Systems',status:'complete',items:['GLB/KTX2/Draco/Meshopt asset pipeline','Rapier WASM physics foundation','PBR material system','geometry + animation LOD','weapon/character rig loaders','multiplayer foundations','dynamic quality profiles','permanent resident / weapons_player / dlc_weapons audio']},
  {id:3,name:'Playable Production Integration',status:'active',items:['real M4A1, service pistol, AK-74, MP5A5 and AWM viewmodels','rigged first-person arms','animated operator targets','Quaternius animation libraries','procedural COD-style weapon weight','reload magazine/bolt mechanics','mouse + touch + standard gamepad','permanent weapon-bank audio + mastering','WebGPU-first cinematic renderer']},
  {id:4,name:'Combat + Effects Polish',status:'active',items:['muzzle flash and sparks','shell ejection','headshots','richer smoke particles','ballistics / penetration / ricochet integration','surface decals','hit reactions','ragdolls','distance/occlusion audio']},
  {id:5,name:'Maps + Visual Fidelity',status:'active',items:['real industrial environment kit','wet-surface art direction','Cyberpunk-inspired emissive local lighting','desktop SSGI + temporal AA','mobile half-resolution GTAO','bloom / ACES / IBL','night vision and weather expansion']},
  {id:6,name:'Online Multiplayer',status:'queued',items:['authoritative simulation','client prediction','server reconciliation','lag compensation','TDM/FFA','rooms','anti-cheat validation']},
  {id:7,name:'Content + Release',status:'queued',items:['full weapon roster','operators/customization','gunsmith','additional maps','procedural modules','PWA cache pass','controller certification','iPhone performance certification']}
];
