import * as THREE from 'three';
import { AudioManager } from './audio/AudioManager.js';
import { AssetManager } from './assets/AssetManager.js';
import { PhysicsWorld } from './physics/PhysicsWorld.js';
import { MaterialSystem } from './rendering/MaterialSystem.js';
import { LODSystem } from './rendering/LODSystem.js';
import { mountRoadmap } from './ui/RoadmapUI.js';

const $=s=>document.querySelector(s);mountRoadmap();
const canvas=$('#game');
const mobile=matchMedia('(pointer:coarse)').matches;
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.75));
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x87929d);scene.fog=new THREE.FogExp2(0x87929d,.0115);
const camera=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.05,260);camera.rotation.order='YXZ';
const clock=new THREE.Clock(),audio=new AudioManager(),assets=new AssetManager(renderer),materials=new MaterialSystem(),lod=new LODSystem(assets),physics=new PhysicsWorld();
let physicsReady=false;physics.init().then(()=>{physicsReady=true;for(const c of pendingPhysics)c()}).catch(e=>console.warn('Rapier unavailable; collision fallback active',e));
const pendingPhysics=[];

scene.add(new THREE.HemisphereLight(0xc9ddff,0x3f3933,1.45));
const sun=new THREE.DirectionalLight(0xffefd1,2.9);sun.position.set(-22,30,15);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-48;sun.shadow.camera.right=48;sun.shadow.camera.top=48;sun.shadow.camera.bottom=-48;scene.add(sun);

const world=new THREE.Group();scene.add(world);const colliders=[];
const mats={concrete:materials.create('concrete',{dirt:.2}),paint:materials.create('paintedConcrete',{dirt:.14}),rust:materials.create('rustedMetal',{rust:.75,dirt:.22}),metal:materials.create('cleanMetal'),wood:materials.create('wood',{dirt:.12}),asphalt:materials.create('asphalt')};
const floor=new THREE.Mesh(new THREE.PlaneGeometry(120,120),mats.asphalt);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;world.add(floor);
pendingPhysics.push(()=>physics.fixedBox({x:0,y:-.25,z:0,hx:60,hy:.25,hz:60}));
function block(x,y,z,sx,sy,sz,mat=mats.concrete){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;world.add(m);colliders.push(new THREE.Box3().setFromObject(m));pendingPhysics.push(()=>physics.fixedBox({x,y,z,hx:sx/2,hy:sy/2,hz:sz/2}));return m}
// Killhouse production blockout: center lane, flank lanes, cover and elevated silhouette.
block(0,2,-24,48,4,2,mats.paint);block(0,2,24,48,4,2,mats.paint);block(-24,2,0,2,4,50,mats.concrete);block(24,2,0,2,4,50,mats.concrete);
block(-9,1.5,-9,9,3,1,mats.wood);block(9,1.5,-9,9,3,1,mats.wood);block(-12,1.5,6,1,3,13);block(12,1.5,6,1,3,13);block(0,1.5,13,14,3,1);block(0,1.5,1,8,3,1);
block(-18,1,-14,4,2,6,mats.rust);block(18,1,14,4,2,6,mats.rust);for(let i=0;i<7;i++)block(-19+i*6,.6,19,2.6,1.2,2.6,i%2?mats.rust:mats.wood);
block(-20,3.8,0,6,.35,20,mats.metal);block(20,3.8,0,6,.35,20,mats.metal);

const targets=[];function addTarget(x,z){const root=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.95,4,8),materials.create('paintedConcrete',{dirt:.05})),head=new THREE.Mesh(new THREE.SphereGeometry(.27,16,10),new THREE.MeshStandardMaterial({color:0x8a7668,roughness:.78}));body.position.y=1.15;head.position.y=2.03;body.castShadow=head.castShadow=true;root.add(body,head);root.position.set(x,0,z);root.userData={health:100,alive:true,respawn:0};scene.add(root);targets.push(root)}
addTarget(0,-17);addTarget(-17,7);addTarget(17,-5);addTarget(6,18);

// FPS viewmodel root. Stage 3 replaces these proxy meshes with a socketed GLB weapon + arm rig.
const viewRoot=new THREE.Group();camera.add(viewRoot);scene.add(camera);const gun=new THREE.Group();viewRoot.add(gun);
const gunMat=new THREE.MeshStandardMaterial({color:0x16191c,roughness:.28,metalness:.86}),steel=new THREE.MeshStandardMaterial({color:0x353a3e,roughness:.22,metalness:.94}),glove=new THREE.MeshStandardMaterial({color:0x22282d,roughness:.8});
const receiver=new THREE.Mesh(new THREE.BoxGeometry(.14,.15,.58),gunMat);receiver.position.set(.20,-.22,-.47);gun.add(receiver);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.58,12),steel);barrel.rotation.x=Math.PI/2;barrel.position.set(.2,-.18,-.94);gun.add(barrel);const mag=new THREE.Mesh(new THREE.BoxGeometry(.105,.33,.17),gunMat);mag.position.set(.18,-.42,-.43);mag.rotation.x=-.12;gun.add(mag);const stock=new THREE.Mesh(new THREE.BoxGeometry(.16,.15,.34),gunMat);stock.position.set(.18,-.22,-.14);gun.add(stock);
const handR=new THREE.Mesh(new THREE.CapsuleGeometry(.075,.36,4,8),glove);handR.rotation.z=-.45;handR.position.set(.28,-.46,-.28);gun.add(handR);const handL=new THREE.Mesh(new THREE.CapsuleGeometry(.075,.42,4,8),glove);handL.rotation.z=.55;handL.position.set(-.04,-.42,-.69);gun.add(handL);const muzzleLight=new THREE.PointLight(0xffb15b,0,4);muzzleLight.position.set(.2,-.18,-1.24);gun.add(muzzleLight);gun.position.set(.19,-.08,.06);

const player={pos:new THREE.Vector3(0,1.72,10),vel:new THREE.Vector3(),yaw:0,pitch:0,height:1.72,crouch:false,slide:0,grounded:true,ammo:30,reserve:90,reloading:false,ads:false,cooldown:0};
const keys={};let started=false,firing=false,joy={x:0,y:0},joyId=null,lookTouch=null;const casings=[];
function collides(pos){const r=.32,feet=pos.y-player.height,b=new THREE.Box3(new THREE.Vector3(pos.x-r,feet,pos.z-r),new THREE.Vector3(pos.x+r,pos.y+.12,pos.z+r));return colliders.some(c=>c.intersectsBox(b))}
function updateAmmo(){$('#ammo').textContent=player.ammo;document.querySelector('.ammo span').textContent='/ '+player.reserve}
function jump(){if(player.grounded&&!player.crouch){player.grounded=false;player.vel.y=6.15}}
function slideOrCrouch(){const moving=keys.KeyW||Math.hypot(joy.x,joy.y)>.7;if(moving&&!player.crouch){player.slide=.58;player.crouch=true;setTimeout(()=>{if(player.slide<=0)player.crouch=false},620)}else player.crouch=!player.crouch}
function reload(){if(player.reloading||player.ammo===30||player.reserve<=0)return;player.reloading=true;$('#statusText').textContent='RELOADING';audio.play('weapons_player','reload',{gain:.4});const st=performance.now(),timer=setInterval(()=>{const t=Math.min(1,(performance.now()-st)/1150);gun.rotation.z=Math.sin(t*Math.PI)*-.44;mag.position.y=-.42-Math.sin(t*Math.PI)*.34;if(t>=1){clearInterval(timer);gun.rotation.z=0;mag.position.y=-.42;const take=Math.min(30-player.ammo,player.reserve);player.ammo+=take;player.reserve-=take;player.reloading=false;updateAmmo();$('#statusText').textContent='READY'}},16)}
function casing(){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,.045,8),new THREE.MeshStandardMaterial({color:0xc39842,roughness:.3,metalness:.9}));mesh.rotation.z=Math.PI/2;const p=new THREE.Vector3(.34,-.20,-.38);camera.localToWorld(p);mesh.position.copy(p);scene.add(mesh);const item={mesh,life:2,vel:new THREE.Vector3(.9+Math.random()*.45,.8+Math.random()*.4,.15-Math.random()*.3).applyQuaternion(camera.quaternion),body:null};if(physicsReady){item.body=physics.dynamicBox({x:p.x,y:p.y,z:p.z,hx:.025,hy:.012,hz:.012,mass:.008,restitution:.22,friction:.65}).body;item.body.setLinvel({x:item.vel.x,y:item.vel.y,z:item.vel.z},true)}casings.push(item)}
function hitmarker(){const h=$('#hitmarker');h.classList.add('show');setTimeout(()=>h.classList.remove('show'),90)}
function shoot(){if(!started||player.reloading||player.cooldown>0||player.ammo<=0)return;player.cooldown=.095;player.ammo--;updateAmmo();audio.playWeaponShot('lmg_combat');muzzleLight.intensity=mobile?12:24;setTimeout(()=>muzzleLight.intensity=0,35);casing();gun.position.z+=.035;gun.rotation.x-=.046;player.pitch=Math.max(-1.45,player.pitch-.012);const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects(targets.filter(t=>t.userData.alive).flatMap(t=>t.children),false)[0];if(!hit)return;const target=targets.find(t=>t.children.includes(hit.object));if(!target)return;target.userData.health-=hit.object.geometry.type==='SphereGeometry'?100:34;hitmarker();if(target.userData.health<=0){target.userData.alive=false;target.visible=false;target.userData.respawn=2.4}}

function updatePlayer(dt){const f=new THREE.Vector3(-Math.sin(player.yaw),0,-Math.cos(player.yaw)),r=new THREE.Vector3(Math.cos(player.yaw),0,-Math.sin(player.yaw));let x=(keys.KeyD?1:0)-(keys.KeyA?1:0)+joy.x,y=(keys.KeyW?1:0)-(keys.KeyS?1:0)-joy.y;const dir=r.multiplyScalar(x).add(f.multiplyScalar(y));if(dir.lengthSq()>1)dir.normalize();const sprint=(keys.ShiftLeft||keys.ShiftRight||Math.hypot(joy.x,joy.y)>.86)&&y>.1;let speed=player.crouch?2.7:sprint?7.4:4.6;if(player.slide>0){speed=9.1*(player.slide/.58);player.slide=Math.max(0,player.slide-dt)}const next=player.pos.clone().addScaledVector(dir,speed*dt),nx=new THREE.Vector3(next.x,player.pos.y,player.pos.z);if(!collides(nx))player.pos.x=next.x;const nz=new THREE.Vector3(player.pos.x,player.pos.y,next.z);if(!collides(nz))player.pos.z=next.z;if(!player.grounded){player.vel.y-=18*dt;player.pos.y+=player.vel.y*dt;if(player.pos.y<=player.height){player.pos.y=player.height;player.vel.y=0;player.grounded=true}}player.height=THREE.MathUtils.lerp(player.height,player.crouch?1.18:1.72,1-Math.exp(-12*dt));if(player.grounded)player.pos.y=player.height;camera.position.copy(player.pos);camera.rotation.y=player.yaw;camera.rotation.x=player.pitch;const moving=dir.lengthSq()>.02,t=performance.now()*.001;camera.position.y+=moving?Math.sin(t*(sprint?14:9))*(sprint?.014:.008):0;gun.position.lerp(player.ads?new THREE.Vector3(-.20,.20,.23):new THREE.Vector3(.19,-.08,.06),1-Math.exp(-14*dt));camera.fov=THREE.MathUtils.lerp(camera.fov,player.ads?59:sprint?79:76,1-Math.exp(-10*dt));camera.updateProjectionMatrix()}

function bindInput(){addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')jump();if(e.code==='KeyR')reload();if(e.code==='KeyC'||e.code==='ControlLeft')slideOrCrouch()});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0)firing=true;if(e.button===2)player.ads=true});addEventListener('mouseup',e=>{if(e.button===0)firing=false;if(e.button===2)player.ads=false});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){player.yaw-=e.movementX*.0022;player.pitch=THREE.MathUtils.clamp(player.pitch-e.movementY*.0022,-1.45,1.45)}});const pad=$('#leftPad'),stick=pad.querySelector('.stick'),reset=()=>{joy={x:0,y:0};stick.style.transform='translate(0,0)'};pad.addEventListener('touchstart',e=>joyId=e.changedTouches[0].identifier,{passive:false});pad.addEventListener('touchmove',e=>{e.preventDefault();const t=[...e.changedTouches].find(v=>v.identifier===joyId);if(!t)return;const b=pad.getBoundingClientRect(),dx=t.clientX-(b.left+b.width/2),dy=t.clientY-(b.top+b.height/2),m=Math.min(38,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);joy={x:Math.cos(a)*m/38,y:Math.sin(a)*m/38};stick.style.transform=`translate(${joy.x*38}px,${joy.y*38}px)`},{passive:false});pad.addEventListener('touchend',reset);const look=$('#lookZone');look.addEventListener('touchstart',e=>{const t=e.changedTouches[0];lookTouch={id:t.identifier,x:t.clientX,y:t.clientY}},{passive:false});look.addEventListener('touchmove',e=>{e.preventDefault();const t=[...e.changedTouches].find(v=>v.identifier===lookTouch?.id);if(!t)return;const dx=t.clientX-lookTouch.x,dy=t.clientY-lookTouch.y;lookTouch.x=t.clientX;lookTouch.y=t.clientY;player.yaw-=dx*.0045;player.pitch=THREE.MathUtils.clamp(player.pitch-dy*.0045,-1.45,1.45)},{passive:false});look.addEventListener('touchend',()=>lookTouch=null);const hold=(el,on,off)=>{el.addEventListener('touchstart',e=>{e.preventDefault();on()},{passive:false});el.addEventListener('touchend',e=>{e.preventDefault();off?.()},{passive:false})};hold($('#fireBtn'),()=>firing=true,()=>firing=false);hold($('#adsBtn'),()=>player.ads=true,()=>player.ads=false);$('#reloadBtn').onclick=reload;$('#jumpBtn').onclick=jump;$('#slideBtn').onclick=slideOrCrouch}
bindInput();

$('#playBtn').onclick=async()=>{started=true;$('#boot').classList.add('hidden');$('#hud').classList.remove('hidden');await audio.unlock();audio.loadPermanent?.().catch(()=>{});if(matchMedia('(pointer:fine)').matches)canvas.requestPointerLock?.()};
$('#audioZip').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;const status=$('#audioStatus');await audio.unlock();audio.clear();let total=0,failed=0;const layers={resident:0,weapons_player:0,dlc_weapons:0};for(let i=0;i<files.length;i++){status.textContent=`Importing pack ${i+1}/${files.length}…`;try{const r=await audio.importZip(files[i]);total+=r.loaded;failed+=r.failed||0;for(const k in layers)layers[k]+=r.layers[k]||0}catch(err){failed++;console.error(err)}}status.textContent=`Audio ready · ${total} WAVs · resident ${layers.resident} · weapons ${layers.weapons_player} · DLC ${layers.dlc_weapons}${failed?` · ${failed} skipped`:''}`};

let frames=0,elapsed=0,lastFps=performance.now();function loop(){requestAnimationFrame(loop);const dt=Math.min(.035,clock.getDelta());if(physicsReady)physics.step(dt);if(started){player.cooldown=Math.max(0,player.cooldown-dt);if(firing)shoot();updatePlayer(dt);gun.rotation.x=THREE.MathUtils.lerp(gun.rotation.x,0,1-Math.exp(-18*dt));for(let i=casings.length-1;i>=0;i--){const c=casings[i];c.life-=dt;if(c.body){const p=c.body.translation(),q=c.body.rotation();c.mesh.position.set(p.x,p.y,p.z);c.mesh.quaternion.set(q.x,q.y,q.z,q.w)}else{c.vel.y-=6*dt;c.mesh.position.addScaledVector(c.vel,dt);if(c.mesh.position.y<.03){c.mesh.position.y=.03;c.vel.multiplyScalar(.3)}}if(c.life<=0){scene.remove(c.mesh);casings.splice(i,1)}}for(const t of targets)if(!t.userData.alive){t.userData.respawn-=dt;if(t.userData.respawn<=0){t.userData.health=100;t.userData.alive=true;t.visible=true}}lod.update(dt,camera)}renderer.render(scene,camera);frames++;elapsed+=dt;if(performance.now()-lastFps>500){$('#fps').textContent=Math.round(frames/elapsed)+' FPS';frames=0;elapsed=0;lastFps=performance.now()}}
loop();
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
window.ProjectStrike={renderer,scene,camera,audio,assets,physics,lod,stage:2};
